import type { Worker, Review } from "./catalog";

export const WORKERS: Worker[] = [
  {
    id: "joka-baptista",
    name: "Joaquim “Joka” Baptista",
    category: "pedreiro",
    neighborhood: "Palanca",
    years: 14,
    rateMin: 9000,
    rateMax: 15000,
    rating: 4.9,
    jobsCount: 86,
    availableToday: true,
    bio: "Obra miúda e muro de vedação. Trabalho com dois ajudantes. Material combinamos à parte.",
    skills: ["Muro", "Reboco", "Laje", "Blocos"],
    responseMins: 18,
    whatsapp: "244923001001",
    reviews: [
      {
        author: "Teresa",
        neighborhood: "Palanca",
        rating: 5,
        text: "Fez o muro de fundo em três dias. Deixou o quintal limpo. Homem de palavra.",
        ago: "há 2 semanas",
      },
      {
        author: "Mauro",
        neighborhood: "Viana",
        rating: 5,
        text: "Reboco da sala ficou direito. Preço combinado, sem surpresa.",
        ago: "há 1 mês",
      },
    ],
  },
  {
    id: "adao-quilombo",
    name: "Adão Quilombo",
    category: "pedreiro",
    neighborhood: "Zango",
    years: 9,
    rateMin: 8000,
    rateMax: 13000,
    rating: 4.7,
    jobsCount: 54,
    availableToday: false,
    bio: "Casas novas no Zango e anexos. Posso levar ajudante se a obra pedir.",
    skills: ["Anexo", "Fundação", "Chão", "Reboco"],
    responseMins: 40,
    whatsapp: "244923001002",
    reviews: [
      {
        author: "Irene",
        neighborhood: "Zango",
        rating: 5,
        text: "Fez o anexo da mama. Chegou cedo todos os dias.",
        ago: "há 3 semanas",
      },
    ],
  },
  {
    id: "nelito-fernandes",
    name: "Nelito Fernandes",
    category: "electricista",
    neighborhood: "Viana",
    years: 8,
    rateMin: 7000,
    rateMax: 12000,
    rating: 4.8,
    jobsCount: 71,
    availableToday: true,
    bio: "Quadro, curtos, ligação de gerador à casa. Levo alicate e disjuntores comuns.",
    skills: ["Quadro", "Tomadas", "Gerador", "LED"],
    responseMins: 12,
    whatsapp: "244923001003",
    reviews: [
      {
        author: "Luzia",
        neighborhood: "Viana",
        rating: 5,
        text: "Resolveu o quadro da casa da mama no mesmo dia. Explicou o que estava queimado.",
        ago: "há 5 dias",
      },
      {
        author: "Paulo",
        neighborhood: "Camama",
        rating: 4,
        text: "Bom trabalho. Só atrasou meia hora no trânsito.",
        ago: "há 3 semanas",
      },
    ],
  },
  {
    id: "catarina-dias",
    name: "Catarina Dias",
    category: "electricista",
    neighborhood: "Kilamba",
    years: 6,
    rateMin: 8000,
    rateMax: 14000,
    rating: 4.9,
    jobsCount: 39,
    availableToday: true,
    bio: "Apartamentos no Kilamba e Talatona. Instalação limpa, sem partir parede à toa.",
    skills: ["Apartamento", "Quadro", "Iluminação"],
    responseMins: 22,
    whatsapp: "244923001004",
    reviews: [
      {
        author: "Hélder",
        neighborhood: "Kilamba",
        rating: 5,
        text: "Trocou o quadro do T3 sem deixar o chão sujo. Rara.",
        ago: "há 1 semana",
      },
    ],
  },
  {
    id: "salvador-mateus",
    name: "Salvador Mateus",
    category: "canalizador",
    neighborhood: "Cazenga",
    years: 11,
    rateMin: 6000,
    rateMax: 11000,
    rating: 4.8,
    jobsCount: 92,
    availableToday: true,
    bio: "Fuga, esgoto entupido, tanque e bomba. Chego de kupapata com a caixa de ferramentas.",
    skills: ["Fuga", "Esgoto", "Bomba", "Tanque"],
    responseMins: 9,
    whatsapp: "244923001005",
    reviews: [
      {
        author: "Deolinda",
        neighborhood: "Cazenga",
        rating: 5,
        text: "A casa estava a alagar. Veio em 40 minutos e parou a água.",
        ago: "há 4 dias",
      },
      {
        author: "Wilson",
        neighborhood: "Hoji-ya-Henda",
        rating: 5,
        text: "Trocou a torneira e o sifão. Preço justo.",
        ago: "há 2 semanas",
      },
    ],
  },
  {
    id: "esperanca-lopes",
    name: "Esperança Lopes",
    category: "canalizador",
    neighborhood: "Cacuaco",
    years: 7,
    rateMin: 6500,
    rateMax: 12000,
    rating: 4.6,
    jobsCount: 41,
    availableToday: false,
    bio: "Casas no Cacuaco e Panguila. Trabalho em cisternas e ligações de tanque.",
    skills: ["Cisterna", "Cano PVC", "Chuveiro"],
    responseMins: 35,
    whatsapp: "244923001006",
    reviews: [
      {
        author: "Nadir",
        neighborhood: "Cacuaco",
        rating: 5,
        text: "Ligou o tanque novo à bomba. Água chegou à laje.",
        ago: "há 1 mês",
      },
    ],
  },
  {
    id: "rosa-manuel",
    name: "Rosa Manuel",
    category: "cabeleireira",
    neighborhood: "Cazenga",
    years: 12,
    rateMin: 2500,
    rateMax: 8000,
    rating: 4.9,
    jobsCount: 210,
    availableToday: true,
    bio: "Atendo em casa, no quintal sombreado. Tranças, corte, permanente. Marcação no WhatsApp.",
    skills: ["Tranças", "Corte", "Permanente", "Crianças"],
    responseMins: 15,
    whatsapp: "244923001007",
    reviews: [
      {
        author: "Amina",
        neighborhood: "Cazenga",
        rating: 5,
        text: "Tranças da miúda aguentaram o mês todo. Mãos leves.",
        ago: "há 6 dias",
      },
      {
        author: "Jacinta",
        neighborhood: "Rangel",
        rating: 5,
        text: "Corte e tratamento. Sai daqui outra pessoa.",
        ago: "há 3 semanas",
      },
    ],
  },
  {
    id: "quinzinho-barbas",
    name: "Quinzinho Barbas",
    category: "cabeleireira",
    neighborhood: "Sambizanga",
    years: 10,
    rateMin: 2000,
    rateMax: 5000,
    rating: 4.7,
    jobsCount: 164,
    availableToday: true,
    bio: "Barba, degradê, linha. Cadeira à porta da loja. Sem espera longa à tarde.",
    skills: ["Barba", "Degradê", "Linha"],
    responseMins: 8,
    whatsapp: "244923001008",
    reviews: [
      {
        author: "Domingos",
        neighborhood: "Sambizanga",
        rating: 5,
        text: "Melhor degradê do bairro. Rápido e limpo.",
        ago: "há 2 dias",
      },
    ],
  },
  {
    id: "helder-pintura",
    name: "Hélder da Silva",
    category: "pintor",
    neighborhood: "Camama",
    years: 9,
    rateMin: 8000,
    rateMax: 14000,
    rating: 4.8,
    jobsCount: 58,
    availableToday: true,
    bio: "Pinto com tinta boa se o cliente trouxer, ou eu compro com factura. Protejo o chão.",
    skills: ["Interior", "Exterior", "Gesso", "Massa"],
    responseMins: 25,
    whatsapp: "244923001009",
    reviews: [
      {
        author: "Maria",
        neighborhood: "Camama",
        rating: 5,
        text: "Sala e dois quartos em dois dias. Cheiro saiu rápido.",
        ago: "há 1 semana",
      },
    ],
  },
  {
    id: "feliciana-tinta",
    name: "Feliciana Sousa",
    category: "pintor",
    neighborhood: "Talatona",
    years: 5,
    rateMin: 10000,
    rateMax: 18000,
    rating: 4.9,
    jobsCount: 27,
    availableToday: false,
    bio: "Acabamento fino em apartamento. Cores combinadas. Trabalho só com ajudante.",
    skills: ["Apartamento", "Acabamento", "Textura"],
    responseMins: 50,
    whatsapp: "244923001010",
    reviews: [
      {
        author: "Bernardo",
        neighborhood: "Talatona",
        rating: 5,
        text: "Pintou o T2 como se fosse casa nova. Detalhe nas caixas.",
        ago: "há 2 semanas",
      },
    ],
  },
  {
    id: "mauro-solda",
    name: "Mauro Capitão",
    category: "soldador",
    neighborhood: "Viana",
    years: 13,
    rateMin: 10000,
    rateMax: 18000,
    rating: 4.8,
    jobsCount: 67,
    availableToday: true,
    bio: "Portão, grade, tanque de água em chapa. Máquina minha. Medida no local.",
    skills: ["Portão", "Grade", "Tanque", "Corrimão"],
    responseMins: 20,
    whatsapp: "244923001011",
    reviews: [
      {
        author: "Salvador",
        neighborhood: "Viana",
        rating: 5,
        text: "Portão novo em chapa. Fechou direito à primeira.",
        ago: "há 8 dias",
      },
      {
        author: "Teresa",
        neighborhood: "Benfica",
        rating: 4,
        text: "Grade da janela sólida. Entrega atrasou um dia.",
        ago: "há 1 mês",
      },
    ],
  },
  {
    id: "nadir-ferro",
    name: "Nadir Ferreira",
    category: "soldador",
    neighborhood: "Benfica",
    years: 8,
    rateMin: 9000,
    rateMax: 16000,
    rating: 4.6,
    jobsCount: 33,
    availableToday: true,
    bio: "Estruturas pequenas e reparação de portão. Posso ir ao ferro com o cliente.",
    skills: ["Reparação", "Portão", "Estrutura"],
    responseMins: 30,
    whatsapp: "244923001012",
    reviews: [
      {
        author: "Joaquim",
        neighborhood: "Benfica",
        rating: 5,
        text: "Soldou o portão que os miúdos partiram. Ficou mais forte.",
        ago: "há 12 dias",
      },
    ],
  },
  {
    id: "paulo-gerador",
    name: "Paulo Kiala",
    category: "gerador",
    neighborhood: "Cazenga",
    years: 10,
    rateMin: 10000,
    rateMax: 20000,
    rating: 4.9,
    jobsCount: 88,
    availableToday: true,
    bio: "Avulso, óleo, filtro, arranque. Trabalho em geradores de casa e de cantina.",
    skills: ["Avulso", "Arranque", "Revisão", "Transferência"],
    responseMins: 11,
    whatsapp: "244923001013",
    reviews: [
      {
        author: "Rosa",
        neighborhood: "Cazenga",
        rating: 5,
        text: "O gerador da cantina não pega. Veio à noite e deixou a trabalhar.",
        ago: "há 3 dias",
      },
      {
        author: "Adão",
        neighborhood: "Palanca",
        rating: 5,
        text: "Revisão completa. Explicou o consumo de gasóleo.",
        ago: "há 3 semanas",
      },
    ],
  },
  {
    id: "wilson-motores",
    name: "Wilson Monteiro",
    category: "gerador",
    neighborhood: "Hoji-ya-Henda",
    years: 7,
    rateMin: 9000,
    rateMax: 17000,
    rating: 4.7,
    jobsCount: 45,
    availableToday: false,
    bio: "Honda, Kipor, chineses. Peças se houver na Roque; senão digo o prazo.",
    skills: ["Kipor", "Honda", "Peças"],
    responseMins: 28,
    whatsapp: "244923001014",
    reviews: [
      {
        author: "Luzia",
        neighborhood: "Hoji-ya-Henda",
        rating: 5,
        text: "Trocou o avulso e o filtro. Barulho baixou.",
        ago: "há 2 semanas",
      },
    ],
  },
  {
    id: "domingos-madeira",
    name: "Domingos Chitata",
    category: "marceneiro",
    neighborhood: "Rangel",
    years: 16,
    rateMin: 12000,
    rateMax: 25000,
    rating: 4.9,
    jobsCount: 61,
    availableToday: false,
    bio: "Portas, roupeiros, cozinha. Meço, desenho no caderno, confirmo preço antes de cortar.",
    skills: ["Roupeiro", "Porta", "Cozinha", "Cama"],
    responseMins: 45,
    whatsapp: "244923001015",
    reviews: [
      {
        author: "Catarina",
        neighborhood: "Rangel",
        rating: 5,
        text: "Roupeiro de três portas. Madeira boa, dobradiças a sério.",
        ago: "há 1 mês",
      },
    ],
  },
  {
    id: "jacinta-moveis",
    name: "Jacinta Ndala",
    category: "marceneiro",
    neighborhood: "Maianga",
    years: 8,
    rateMin: 11000,
    rateMax: 22000,
    rating: 4.8,
    jobsCount: 29,
    availableToday: true,
    bio: "Móveis à medida para T1 e T2. Melamina e madeira maciça.",
    skills: ["Melamina", "Prateleiras", "Secretária"],
    responseMins: 33,
    whatsapp: "244923001016",
    reviews: [
      {
        author: "Hélder",
        neighborhood: "Maianga",
        rating: 5,
        text: "Aproveitou um recanto morto. Ficou uma secretária perfeita.",
        ago: "há 9 dias",
      },
    ],
  },
  {
    id: "teresa-casa",
    name: "Teresa Ganga",
    category: "limpeza",
    neighborhood: "Kilamba",
    years: 6,
    rateMin: 5000,
    rateMax: 9000,
    rating: 4.8,
    jobsCount: 73,
    availableToday: true,
    bio: "Casa e escritório. Levo produtos se pedires. Pós-obra também, com tempo extra.",
    skills: ["Casa", "Pós-obra", "Escritório"],
    responseMins: 16,
    whatsapp: "244923001017",
    reviews: [
      {
        author: "Feliciana",
        neighborhood: "Kilamba",
        rating: 5,
        text: "Deixou o T3 a brilhar antes dos visitas. Pontual.",
        ago: "há 4 dias",
      },
    ],
  },
  {
    id: "irene-brilho",
    name: "Irene Baptista",
    category: "limpeza",
    neighborhood: "Talatona",
    years: 4,
    rateMin: 6000,
    rateMax: 10000,
    rating: 4.7,
    jobsCount: 38,
    availableToday: true,
    bio: "Trabalho sozinha ou com colega para casas grandes. Referências no bairro.",
    skills: ["Casa", "Vidros", "Roupa"],
    responseMins: 20,
    whatsapp: "244923001018",
    reviews: [
      {
        author: "Nadir",
        neighborhood: "Talatona",
        rating: 5,
        text: "Discreta e rápida. A cozinha ficou nova.",
        ago: "há 1 semana",
      },
    ],
  },
  {
    id: "mateus-oficina",
    name: "Mateus “Teco” António",
    category: "mecanico",
    neighborhood: "Viana",
    years: 15,
    rateMin: 7000,
    rateMax: 15000,
    rating: 4.8,
    jobsCount: 120,
    availableToday: true,
    bio: "Carro e moto. Diagnóstico honesto — se não for, digo. Oficina no fundo do quintal.",
    skills: ["Travões", "Embraiagem", "Moto", "Revisão"],
    responseMins: 14,
    whatsapp: "244923001019",
    reviews: [
      {
        author: "Paulo",
        neighborhood: "Viana",
        rating: 5,
        text: "A Toyota estava a gastar óleo. Apertou e explicou. Sem conto.",
        ago: "há 6 dias",
      },
    ],
  },
  {
    id: "aminah-motos",
    name: "Amina dos Santos",
    category: "mecanico",
    neighborhood: "Cacuaco",
    years: 5,
    rateMin: 5000,
    rateMax: 10000,
    rating: 4.9,
    jobsCount: 64,
    availableToday: true,
    bio: "Kupapatas e motos chinesas. Corrente, pneu, electricidade da moto.",
    skills: ["Kupapata", "Pneus", "Elétrica"],
    responseMins: 10,
    whatsapp: "244923001020",
    reviews: [
      {
        author: "Quinzinho",
        neighborhood: "Cacuaco",
        rating: 5,
        text: "A moto não pegava. Fio solto. 20 minutos, preço de verdade.",
        ago: "há 2 dias",
      },
    ],
  },
  {
    id: "luzia-linha",
    name: "Luzia Pimentel",
    category: "costureira",
    neighborhood: "Sambizanga",
    years: 18,
    rateMin: 3000,
    rateMax: 12000,
    rating: 5,
    jobsCount: 95,
    availableToday: false,
    bio: "Fatos, fardas, ajustes. Prova em casa. Entrega combinada, sem faltar à missa de domingo.",
    skills: ["Fato", "Ajuste", "Farda", "Vestido"],
    responseMins: 40,
    whatsapp: "244923001021",
    reviews: [
      {
        author: "Maria",
        neighborhood: "Sambizanga",
        rating: 5,
        text: "O fato do marido para o casamento. Caía que nem luva.",
        ago: "há 3 semanas",
      },
    ],
  },
  {
    id: "deolinda-agulha",
    name: "Deolinda Cruz",
    category: "costureira",
    neighborhood: "Palanca",
    years: 9,
    rateMin: 2500,
    rateMax: 9000,
    rating: 4.7,
    jobsCount: 52,
    availableToday: true,
    bio: "Uniformes escolares e arranjos rápidos. Máquina em casa, na Palanca.",
    skills: ["Uniforme", "Bainha", "Zíper"],
    responseMins: 18,
    whatsapp: "244923001022",
    reviews: [
      {
        author: "Esperança",
        neighborhood: "Palanca",
        rating: 5,
        text: "Três fardas da escola em dois dias. Pontos direitos.",
        ago: "há 1 semana",
      },
    ],
  },
  {
    id: "bernardo-frio",
    name: "Bernardo Fria",
    category: "ac",
    neighborhood: "Talatona",
    years: 11,
    rateMin: 12000,
    rateMax: 22000,
    rating: 4.8,
    jobsCount: 77,
    availableToday: true,
    bio: "Instalação e recarga de gás. Split até 24 mil BTU. Limpeza de filtros incluída na visita de revisão.",
    skills: ["Instalação", "Gás", "Limpeza", "Split"],
    responseMins: 24,
    whatsapp: "244923001023",
    reviews: [
      {
        author: "Catarina",
        neighborhood: "Talatona",
        rating: 5,
        text: "Instalou o split no quarto. Furo limpo, água a escorrer para fora.",
        ago: "há 5 dias",
      },
    ],
  },
  {
    id: "helder-split",
    name: "Hélder Split",
    category: "ac",
    neighborhood: "Kilamba",
    years: 6,
    rateMin: 10000,
    rateMax: 18000,
    rating: 4.6,
    jobsCount: 34,
    availableToday: true,
    bio: "Revisão e instalação em apartamento. Trabalho ao sábado de manhã.",
    skills: ["Revisão", "Instalação", "Apartamento"],
    responseMins: 32,
    whatsapp: "244923001024",
    reviews: [
      {
        author: "Wilson",
        neighborhood: "Kilamba",
        rating: 4,
        text: "Limpeza profunda. O ar voltou a gelar. Um pouco de pó no chão.",
        ago: "há 2 semanas",
      },
    ],
  },
];