import { createFileRoute, Link, useNavigate } from "@tanstack/react-router";
import { useState, type FormEvent } from "react";
import { CheckCircle2, Pencil } from "lucide-react";
import { toast } from "sonner";
import { CATEGORIES, NEIGHBORHOODS } from "@/lib/catalog";
import { getOwnedProfessional, registerProfessional, updateOwnedProfessional } from "@/lib/account-workflows";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";

export const Route = createFileRoute("/profissional/cadastrar")({ loader: () => getOwnedProfessional(), component: PerfilProfissional });
function PerfilProfissional() {
  const existing = Route.useLoaderData(); const navigate = useNavigate(); const [busy, setBusy] = useState(false); const [editing, setEditing] = useState(!existing); const [name, setName] = useState(existing?.name ?? ""); const [bio, setBio] = useState(existing?.bio ?? ""); const [whatsapp, setWhatsapp] = useState(existing?.whatsapp ?? ""); const [category, setCategory] = useState(existing?.category ?? CATEGORIES[0].slug); const [neighborhood, setNeighborhood] = useState<string>(existing?.neighborhood ?? NEIGHBORHOODS[0]); const [min, setMin] = useState(existing?.rate_min.toString() ?? ""); const [max, setMax] = useState(existing?.rate_max.toString() ?? ""); const [skills, setSkills] = useState(existing?.skills.join(", ") ?? ""); const [availableToday, setAvailableToday] = useState(existing?.available_today ?? false);
  async function submit(event: FormEvent) { event.preventDefault(); setBusy(true); const data = { name, category, neighborhood, bio, whatsapp, rateMin: Number(min), rateMax: Number(max), skills: skills.split(",").map((item) => item.trim()).filter(Boolean) }; try { const result = existing ? await updateOwnedProfessional({ data: { ...data, availableToday } }) : await registerProfessional({ data }); toast.success(existing ? "Perfil profissional atualizado." : "Perfil profissional criado."); setEditing(false); await navigate({ to: "/profissionais/$id", params: { id: result.id } }); } catch (error) { toast.error(error instanceof Error ? error.message : "Não foi possível guardar o perfil."); } finally { setBusy(false); } }
  if (existing && !editing) return <section className="space-y-5"><div className="rounded-2xl bg-surface p-6 shadow-[var(--shadow-card)]"><div className="flex items-start gap-3"><CheckCircle2 className="mt-0.5 size-6 text-primary" /><div><p className="text-sm font-medium text-primary">Perfil profissional ativo</p><h1 className="mt-1 font-display text-2xl font-semibold">{existing.name}</h1><p className="mt-2 text-sm text-muted">Os teus dados estão guardados e já podem receber pedidos de {existing.category}.</p></div></div><div className="mt-5 flex flex-col gap-2 sm:flex-row"><Button onClick={() => setEditing(true)}><Pencil className="size-4" />Editar perfil</Button><Button asChild variant="outline"><Link to="/profissionais/$id" params={{ id: existing.id }}>Ver perfil público</Link></Button><Button asChild variant="outline"><Link to="/profissional/pedidos">Ver pedidos do meu ofício</Link></Button></div></div></section>;
  return <form onSubmit={submit} className="space-y-5"><header><p className="text-sm font-medium text-primary">Área profissional</p><h1 className="font-display text-2xl font-semibold">{existing ? "Editar perfil profissional" : "Criar perfil profissional"}</h1><p className="mt-1 text-sm text-muted">Os dados ficam associados à tua conta e são mostrados no teu perfil público.</p></header><div className="space-y-2"><Label htmlFor="name">Nome profissional</Label><Input id="name" required value={name} onChange={(e) => setName(e.target.value)} /></div><div className="grid gap-4 sm:grid-cols-2"><div className="space-y-2"><Label>Ofício</Label><select value={category} onChange={(e) => setCategory(e.target.value)} className="h-11 w-full rounded-md border border-border bg-surface px-3">{CATEGORIES.map((item) => <option key={item.slug} value={item.slug}>{item.name}</option>)}</select></div><div className="space-y-2"><Label>Bairro</Label><select value={neighborhood} onChange={(e) => setNeighborhood(e.target.value)} className="h-11 w-full rounded-md border border-border bg-surface px-3">{NEIGHBORHOODS.map((item) => <option key={item}>{item}</option>)}</select></div></div><div className="space-y-2"><Label htmlFor="bio">Sobre o teu trabalho</Label><Textarea id="bio" required minLength={20} value={bio} onChange={(e) => setBio(e.target.value)} /></div><div className="grid gap-4 sm:grid-cols-2"><div className="space-y-2"><Label htmlFor="min">Preço mínimo (Kz)</Label><Input id="min" required inputMode="numeric" value={min} onChange={(e) => setMin(e.target.value)} /></div><div className="space-y-2"><Label htmlFor="max">Preço máximo (Kz)</Label><Input id="max" required inputMode="numeric" value={max} onChange={(e) => setMax(e.target.value)} /></div></div><div className="space-y-2"><Label htmlFor="skills">Serviços, separados por vírgula</Label><Input id="skills" required value={skills} onChange={(e) => setSkills(e.target.value)} placeholder="Reparações, instalações" /></div><div className="space-y-2"><Label htmlFor="whatsapp">WhatsApp</Label><Input id="whatsapp" required value={whatsapp} onChange={(e) => setWhatsapp(e.target.value)} placeholder="2449…" /></div>{existing ? <label className="flex min-h-11 items-center gap-3 rounded-xl border border-border bg-surface px-3 text-sm"><input type="checkbox" checked={availableToday} onChange={(e) => setAvailableToday(e.target.checked)} />Estou disponível hoje</label> : null}<div className="flex gap-2"><Button type="submit" size="lg" className="flex-1" disabled={busy}>{busy ? "A guardar…" : existing ? "Guardar alterações" : "Criar perfil profissional"}</Button>{existing ? <Button type="button" size="lg" variant="outline" onClick={() => setEditing(false)}>Cancelar</Button> : null}</div></form>;
}
