/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ComoFuncionaRouteImport } from './routes/como-funciona'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as GuardadosRouteImport } from './routes/guardados'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PedirRouteImport } from './routes/pedir'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthConfirmRouteImport } from './routes/auth/confirm'
import { Route as OficiosIndexRouteImport } from './routes/oficios.index'
import { Route as OficiosSlugRouteImport } from './routes/oficios.$slug'
import { Route as PedidosIndexRouteImport } from './routes/pedidos.index'
import { Route as PedidosIdRouteImport } from './routes/pedidos.$id'
import { Route as ProfissionaisIdRouteImport } from './routes/profissionais.$id'
import { Route as ProfissionalCadastrarRouteImport } from './routes/profissional.cadastrar'
import { Route as ProfissionalPedidosRouteImport } from './routes/profissional.pedidos'
import { Route as ApiAuthRestRouteImport } from './routes/api/auth/$rest'
import { Route as ApiAuthRest_newRouteImport } from './routes/api/auth/$rest_new'
import { Route as ApiAuthGetSessionRouteImport } from './routes/api/auth/get-session'
import { Route as ApiAuthProvidersRouteImport } from './routes/api/auth/providers'
import { Route as ApiAuthSignOutRouteImport } from './routes/api/auth/sign-out'
import { Route as ApiDebugAuthRouteImport } from './routes/api/debug/auth'
import { Route as ApiDebugEnvRouteImport } from './routes/api/debug/env'
import { Route as ApiPushSubscribeRouteImport } from './routes/api/push/subscribe'
import { Route as ApiPushUnsubscribeRouteImport } from './routes/api/push/unsubscribe'
import { Route as ApiPushVapidStatusRouteImport } from './routes/api/push/vapid-status'
import { Route as ApiUploadAvatarRouteImport } from './routes/api/upload/avatar'
import { Route as ApiUploadDeleteRouteImport } from './routes/api/upload/delete'
import { Route as ApiUploadPortfolioRouteImport } from './routes/api/upload/portfolio'
import { Route as ApiAuthCallbackGithubRouteImport } from './routes/api/auth/callback/github'
import { Route as ApiAuthCallbackGoogleRouteImport } from './routes/api/auth/callback/google'
import { Route as ApiAuthSignInOauth2RouteImport } from './routes/api/auth/sign-in/oauth2'
import { Route as ApiAuthSignInSocialRouteImport } from './routes/api/auth/sign-in/social'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComoFuncionaRoute = ComoFuncionaRouteImport.update({
  id: '/como-funciona',
  path: '/como-funciona',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const GuardadosRoute = GuardadosRouteImport.update({
  id: '/guardados',
  path: '/guardados',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PedirRoute = PedirRouteImport.update({
  id: '/pedir',
  path: '/pedir',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthConfirmRoute = AuthConfirmRouteImport.update({
  id: '/auth/confirm',
  path: '/auth/confirm',
  getParentRoute: () => rootRouteImport,
} as any)
const OficiosIndexRoute = OficiosIndexRouteImport.update({
  id: '/oficios/',
  path: '/oficios/',
  getParentRoute: () => rootRouteImport,
} as any)
const OficiosSlugRoute = OficiosSlugRouteImport.update({
  id: '/oficios/$slug',
  path: '/oficios/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PedidosIndexRoute = PedidosIndexRouteImport.update({
  id: '/pedidos/',
  path: '/pedidos/',
  getParentRoute: () => rootRouteImport,
} as any)
const PedidosIdRoute = PedidosIdRouteImport.update({
  id: '/pedidos/$id',
  path: '/pedidos/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfissionaisIdRoute = ProfissionaisIdRouteImport.update({
  id: '/profissionais/$id',
  path: '/profissionais/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfissionalCadastrarRoute = ProfissionalCadastrarRouteImport.update({
  id: '/profissional/cadastrar',
  path: '/profissional/cadastrar',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfissionalPedidosRoute = ProfissionalPedidosRouteImport.update({
  id: '/profissional/pedidos',
  path: '/profissional/pedidos',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthRestRoute = ApiAuthRestRouteImport.update({
  id: '/api/auth/$rest',
  path: '/api/auth/$rest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthRest_newRoute = ApiAuthRest_newRouteImport.update({
  id: '/api/auth/$rest_new',
  path: '/api/auth/$rest_new',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthGetSessionRoute = ApiAuthGetSessionRouteImport.update({
  id: '/api/auth/get-session',
  path: '/api/auth/get-session',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthProvidersRoute = ApiAuthProvidersRouteImport.update({
  id: '/api/auth/providers',
  path: '/api/auth/providers',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSignOutRoute = ApiAuthSignOutRouteImport.update({
  id: '/api/auth/sign-out',
  path: '/api/auth/sign-out',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDebugAuthRoute = ApiDebugAuthRouteImport.update({
  id: '/api/debug/auth',
  path: '/api/debug/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDebugEnvRoute = ApiDebugEnvRouteImport.update({
  id: '/api/debug/env',
  path: '/api/debug/env',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPushSubscribeRoute = ApiPushSubscribeRouteImport.update({
  id: '/api/push/subscribe',
  path: '/api/push/subscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPushUnsubscribeRoute = ApiPushUnsubscribeRouteImport.update({
  id: '/api/push/unsubscribe',
  path: '/api/push/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPushVapidStatusRoute = ApiPushVapidStatusRouteImport.update({
  id: '/api/push/vapid-status',
  path: '/api/push/vapid-status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadAvatarRoute = ApiUploadAvatarRouteImport.update({
  id: '/api/upload/avatar',
  path: '/api/upload/avatar',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadDeleteRoute = ApiUploadDeleteRouteImport.update({
  id: '/api/upload/delete',
  path: '/api/upload/delete',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadPortfolioRoute = ApiUploadPortfolioRouteImport.update({
  id: '/api/upload/portfolio',
  path: '/api/upload/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthCallbackGithubRoute = ApiAuthCallbackGithubRouteImport.update({
  id: '/api/auth/callback/github',
  path: '/api/auth/callback/github',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthCallbackGoogleRoute = ApiAuthCallbackGoogleRouteImport.update({
  id: '/api/auth/callback/google',
  path: '/api/auth/callback/google',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSignInOauth2Route = ApiAuthSignInOauth2RouteImport.update({
  id: '/api/auth/sign-in/oauth2',
  path: '/api/auth/sign-in/oauth2',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSignInSocialRoute = ApiAuthSignInSocialRouteImport.update({
  id: '/api/auth/sign-in/social',
  path: '/api/auth/sign-in/social',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/guardados': typeof GuardadosRoute
  '/login': typeof LoginRoute
  '/pedir': typeof PedirRoute
  '/reset-password': typeof ResetPasswordRoute
  '/auth/confirm': typeof AuthConfirmRoute
  '/oficios/$slug': typeof OficiosSlugRoute
  '/pedidos/$id': typeof PedidosIdRoute
  '/profissionais/$id': typeof ProfissionaisIdRoute
  '/profissional/cadastrar': typeof ProfissionalCadastrarRoute
  '/profissional/pedidos': typeof ProfissionalPedidosRoute
  '/oficios/': typeof OficiosIndexRoute
  '/pedidos/': typeof PedidosIndexRoute
  '/api/auth/$rest': typeof ApiAuthRestRoute
  '/api/auth/$rest_new': typeof ApiAuthRest_newRoute
  '/api/auth/get-session': typeof ApiAuthGetSessionRoute
  '/api/auth/providers': typeof ApiAuthProvidersRoute
  '/api/auth/sign-out': typeof ApiAuthSignOutRoute
  '/api/debug/auth': typeof ApiDebugAuthRoute
  '/api/debug/env': typeof ApiDebugEnvRoute
  '/api/push/subscribe': typeof ApiPushSubscribeRoute
  '/api/push/unsubscribe': typeof ApiPushUnsubscribeRoute
  '/api/push/vapid-status': typeof ApiPushVapidStatusRoute
  '/api/upload/avatar': typeof ApiUploadAvatarRoute
  '/api/upload/delete': typeof ApiUploadDeleteRoute
  '/api/upload/portfolio': typeof ApiUploadPortfolioRoute
  '/api/auth/callback/github': typeof ApiAuthCallbackGithubRoute
  '/api/auth/callback/google': typeof ApiAuthCallbackGoogleRoute
  '/api/auth/sign-in/oauth2': typeof ApiAuthSignInOauth2Route
  '/api/auth/sign-in/social': typeof ApiAuthSignInSocialRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/guardados': typeof GuardadosRoute
  '/login': typeof LoginRoute
  '/pedir': typeof PedirRoute
  '/reset-password': typeof ResetPasswordRoute
  '/auth/confirm': typeof AuthConfirmRoute
  '/oficios/$slug': typeof OficiosSlugRoute
  '/pedidos/$id': typeof PedidosIdRoute
  '/profissionais/$id': typeof ProfissionaisIdRoute
  '/profissional/cadastrar': typeof ProfissionalCadastrarRoute
  '/profissional/pedidos': typeof ProfissionalPedidosRoute
  '/oficios': typeof OficiosIndexRoute
  '/pedidos': typeof PedidosIndexRoute
  '/api/auth/$rest': typeof ApiAuthRestRoute
  '/api/auth/$rest_new': typeof ApiAuthRest_newRoute
  '/api/auth/get-session': typeof ApiAuthGetSessionRoute
  '/api/auth/providers': typeof ApiAuthProvidersRoute
  '/api/auth/sign-out': typeof ApiAuthSignOutRoute
  '/api/debug/auth': typeof ApiDebugAuthRoute
  '/api/debug/env': typeof ApiDebugEnvRoute
  '/api/push/subscribe': typeof ApiPushSubscribeRoute
  '/api/push/unsubscribe': typeof ApiPushUnsubscribeRoute
  '/api/push/vapid-status': typeof ApiPushVapidStatusRoute
  '/api/upload/avatar': typeof ApiUploadAvatarRoute
  '/api/upload/delete': typeof ApiUploadDeleteRoute
  '/api/upload/portfolio': typeof ApiUploadPortfolioRoute
  '/api/auth/callback/github': typeof ApiAuthCallbackGithubRoute
  '/api/auth/callback/google': typeof ApiAuthCallbackGoogleRoute
  '/api/auth/sign-in/oauth2': typeof ApiAuthSignInOauth2Route
  '/api/auth/sign-in/social': typeof ApiAuthSignInSocialRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/guardados': typeof GuardadosRoute
  '/login': typeof LoginRoute
  '/pedir': typeof PedirRoute
  '/reset-password': typeof ResetPasswordRoute
  '/auth/confirm': typeof AuthConfirmRoute
  '/oficios/$slug': typeof OficiosSlugRoute
  '/pedidos/$id': typeof PedidosIdRoute
  '/profissionais/$id': typeof ProfissionaisIdRoute
  '/profissional/cadastrar': typeof ProfissionalCadastrarRoute
  '/profissional/pedidos': typeof ProfissionalPedidosRoute
  '/oficios/': typeof OficiosIndexRoute
  '/pedidos/': typeof PedidosIndexRoute
  '/api/auth/$rest': typeof ApiAuthRestRoute
  '/api/auth/$rest_new': typeof ApiAuthRest_newRoute
  '/api/auth/get-session': typeof ApiAuthGetSessionRoute
  '/api/auth/providers': typeof ApiAuthProvidersRoute
  '/api/auth/sign-out': typeof ApiAuthSignOutRoute
  '/api/debug/auth': typeof ApiDebugAuthRoute
  '/api/debug/env': typeof ApiDebugEnvRoute
  '/api/push/subscribe': typeof ApiPushSubscribeRoute
  '/api/push/unsubscribe': typeof ApiPushUnsubscribeRoute
  '/api/push/vapid-status': typeof ApiPushVapidStatusRoute
  '/api/upload/avatar': typeof ApiUploadAvatarRoute
  '/api/upload/delete': typeof ApiUploadDeleteRoute
  '/api/upload/portfolio': typeof ApiUploadPortfolioRoute
  '/api/auth/callback/github': typeof ApiAuthCallbackGithubRoute
  '/api/auth/callback/google': typeof ApiAuthCallbackGoogleRoute
  '/api/auth/sign-in/oauth2': typeof ApiAuthSignInOauth2Route
  '/api/auth/sign-in/social': typeof ApiAuthSignInSocialRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/como-funciona'
    | '/configuracoes'
    | '/guardados'
    | '/login'
    | '/pedir'
    | '/reset-password'
    | '/auth/confirm'
    | '/oficios/$slug'
    | '/pedidos/$id'
    | '/profissionais/$id'
    | '/profissional/cadastrar'
    | '/profissional/pedidos'
    | '/oficios/'
    | '/pedidos/'
    | '/api/auth/$rest'
    | '/api/auth/$rest_new'
    | '/api/auth/get-session'
    | '/api/auth/providers'
    | '/api/auth/sign-out'
    | '/api/debug/auth'
    | '/api/debug/env'
    | '/api/push/subscribe'
    | '/api/push/unsubscribe'
    | '/api/push/vapid-status'
    | '/api/upload/avatar'
    | '/api/upload/delete'
    | '/api/upload/portfolio'
    | '/api/auth/callback/github'
    | '/api/auth/callback/google'
    | '/api/auth/sign-in/oauth2'
    | '/api/auth/sign-in/social'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/como-funciona'
    | '/configuracoes'
    | '/guardados'
    | '/login'
    | '/pedir'
    | '/reset-password'
    | '/auth/confirm'
    | '/oficios/$slug'
    | '/pedidos/$id'
    | '/profissionais/$id'
    | '/profissional/cadastrar'
    | '/profissional/pedidos'
    | '/oficios'
    | '/pedidos'
    | '/api/auth/$rest'
    | '/api/auth/$rest_new'
    | '/api/auth/get-session'
    | '/api/auth/providers'
    | '/api/auth/sign-out'
    | '/api/debug/auth'
    | '/api/debug/env'
    | '/api/push/subscribe'
    | '/api/push/unsubscribe'
    | '/api/push/vapid-status'
    | '/api/upload/avatar'
    | '/api/upload/delete'
    | '/api/upload/portfolio'
    | '/api/auth/callback/github'
    | '/api/auth/callback/google'
    | '/api/auth/sign-in/oauth2'
    | '/api/auth/sign-in/social'
  id:
    | '__root__'
    | '/'
    | '/como-funciona'
    | '/configuracoes'
    | '/guardados'
    | '/login'
    | '/pedir'
    | '/reset-password'
    | '/auth/confirm'
    | '/oficios/$slug'
    | '/pedidos/$id'
    | '/profissionais/$id'
    | '/profissional/cadastrar'
    | '/profissional/pedidos'
    | '/oficios/'
    | '/pedidos/'
    | '/api/auth/$rest'
    | '/api/auth/$rest_new'
    | '/api/auth/get-session'
    | '/api/auth/providers'
    | '/api/auth/sign-out'
    | '/api/debug/auth'
    | '/api/debug/env'
    | '/api/push/subscribe'
    | '/api/push/unsubscribe'
    | '/api/push/vapid-status'
    | '/api/upload/avatar'
    | '/api/upload/delete'
    | '/api/upload/portfolio'
    | '/api/auth/callback/github'
    | '/api/auth/callback/google'
    | '/api/auth/sign-in/oauth2'
    | '/api/auth/sign-in/social'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ComoFuncionaRoute: typeof ComoFuncionaRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  GuardadosRoute: typeof GuardadosRoute
  LoginRoute: typeof LoginRoute
  PedirRoute: typeof PedirRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  AuthConfirmRoute: typeof AuthConfirmRoute
  OficiosSlugRoute: typeof OficiosSlugRoute
  PedidosIdRoute: typeof PedidosIdRoute
  ProfissionaisIdRoute: typeof ProfissionaisIdRoute
  ProfissionalCadastrarRoute: typeof ProfissionalCadastrarRoute
  ProfissionalPedidosRoute: typeof ProfissionalPedidosRoute
  OficiosIndexRoute: typeof OficiosIndexRoute
  PedidosIndexRoute: typeof PedidosIndexRoute
  ApiAuthRestRoute: typeof ApiAuthRestRoute
  ApiAuthRest_newRoute: typeof ApiAuthRest_newRoute
  ApiAuthGetSessionRoute: typeof ApiAuthGetSessionRoute
  ApiAuthProvidersRoute: typeof ApiAuthProvidersRoute
  ApiAuthSignOutRoute: typeof ApiAuthSignOutRoute
  ApiDebugAuthRoute: typeof ApiDebugAuthRoute
  ApiDebugEnvRoute: typeof ApiDebugEnvRoute
  ApiPushSubscribeRoute: typeof ApiPushSubscribeRoute
  ApiPushUnsubscribeRoute: typeof ApiPushUnsubscribeRoute
  ApiPushVapidStatusRoute: typeof ApiPushVapidStatusRoute
  ApiUploadAvatarRoute: typeof ApiUploadAvatarRoute
  ApiUploadDeleteRoute: typeof ApiUploadDeleteRoute
  ApiUploadPortfolioRoute: typeof ApiUploadPortfolioRoute
  ApiAuthCallbackGithubRoute: typeof ApiAuthCallbackGithubRoute
  ApiAuthCallbackGoogleRoute: typeof ApiAuthCallbackGoogleRoute
  ApiAuthSignInOauth2Route: typeof ApiAuthSignInOauth2Route
  ApiAuthSignInSocialRoute: typeof ApiAuthSignInSocialRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/como-funciona': {
      id: '/como-funciona'
      path: '/como-funciona'
      fullPath: '/como-funciona'
      preLoaderRoute: typeof ComoFuncionaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guardados': {
      id: '/guardados'
      path: '/guardados'
      fullPath: '/guardados'
      preLoaderRoute: typeof GuardadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedir': {
      id: '/pedir'
      path: '/pedir'
      fullPath: '/pedir'
      preLoaderRoute: typeof PedirRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/confirm': {
      id: '/auth/confirm'
      path: '/auth/confirm'
      fullPath: '/auth/confirm'
      preLoaderRoute: typeof AuthConfirmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oficios/': {
      id: '/oficios/'
      path: '/oficios'
      fullPath: '/oficios/'
      preLoaderRoute: typeof OficiosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oficios/$slug': {
      id: '/oficios/$slug'
      path: '/oficios/$slug'
      fullPath: '/oficios/$slug'
      preLoaderRoute: typeof OficiosSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedidos/': {
      id: '/pedidos/'
      path: '/pedidos'
      fullPath: '/pedidos/'
      preLoaderRoute: typeof PedidosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedidos/$id': {
      id: '/pedidos/$id'
      path: '/pedidos/$id'
      fullPath: '/pedidos/$id'
      preLoaderRoute: typeof PedidosIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profissionais/$id': {
      id: '/profissionais/$id'
      path: '/profissionais/$id'
      fullPath: '/profissionais/$id'
      preLoaderRoute: typeof ProfissionaisIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profissional/cadastrar': {
      id: '/profissional/cadastrar'
      path: '/profissional/cadastrar'
      fullPath: '/profissional/cadastrar'
      preLoaderRoute: typeof ProfissionalCadastrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profissional/pedidos': {
      id: '/profissional/pedidos'
      path: '/profissional/pedidos'
      fullPath: '/profissional/pedidos'
      preLoaderRoute: typeof ProfissionalPedidosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$rest': {
      id: '/api/auth/$rest'
      path: '/api/auth/$rest'
      fullPath: '/api/auth/$rest'
      preLoaderRoute: typeof ApiAuthRestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$rest_new': {
      id: '/api/auth/$rest_new'
      path: '/api/auth/$rest_new'
      fullPath: '/api/auth/$rest_new'
      preLoaderRoute: typeof ApiAuthRest_newRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/get-session': {
      id: '/api/auth/get-session'
      path: '/api/auth/get-session'
      fullPath: '/api/auth/get-session'
      preLoaderRoute: typeof ApiAuthGetSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/providers': {
      id: '/api/auth/providers'
      path: '/api/auth/providers'
      fullPath: '/api/auth/providers'
      preLoaderRoute: typeof ApiAuthProvidersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/sign-out': {
      id: '/api/auth/sign-out'
      path: '/api/auth/sign-out'
      fullPath: '/api/auth/sign-out'
      preLoaderRoute: typeof ApiAuthSignOutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/debug/auth': {
      id: '/api/debug/auth'
      path: '/api/debug/auth'
      fullPath: '/api/debug/auth'
      preLoaderRoute: typeof ApiDebugAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/debug/env': {
      id: '/api/debug/env'
      path: '/api/debug/env'
      fullPath: '/api/debug/env'
      preLoaderRoute: typeof ApiDebugEnvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/push/subscribe': {
      id: '/api/push/subscribe'
      path: '/api/push/subscribe'
      fullPath: '/api/push/subscribe'
      preLoaderRoute: typeof ApiPushSubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/push/unsubscribe': {
      id: '/api/push/unsubscribe'
      path: '/api/push/unsubscribe'
      fullPath: '/api/push/unsubscribe'
      preLoaderRoute: typeof ApiPushUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/push/vapid-status': {
      id: '/api/push/vapid-status'
      path: '/api/push/vapid-status'
      fullPath: '/api/push/vapid-status'
      preLoaderRoute: typeof ApiPushVapidStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/upload/avatar': {
      id: '/api/upload/avatar'
      path: '/api/upload/avatar'
      fullPath: '/api/upload/avatar'
      preLoaderRoute: typeof ApiUploadAvatarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/upload/delete': {
      id: '/api/upload/delete'
      path: '/api/upload/delete'
      fullPath: '/api/upload/delete'
      preLoaderRoute: typeof ApiUploadDeleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/upload/portfolio': {
      id: '/api/upload/portfolio'
      path: '/api/upload/portfolio'
      fullPath: '/api/upload/portfolio'
      preLoaderRoute: typeof ApiUploadPortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/callback/github': {
      id: '/api/auth/callback/github'
      path: '/api/auth/callback/github'
      fullPath: '/api/auth/callback/github'
      preLoaderRoute: typeof ApiAuthCallbackGithubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/callback/google': {
      id: '/api/auth/callback/google'
      path: '/api/auth/callback/google'
      fullPath: '/api/auth/callback/google'
      preLoaderRoute: typeof ApiAuthCallbackGoogleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/sign-in/oauth2': {
      id: '/api/auth/sign-in/oauth2'
      path: '/api/auth/sign-in/oauth2'
      fullPath: '/api/auth/sign-in/oauth2'
      preLoaderRoute: typeof ApiAuthSignInOauth2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/sign-in/social': {
      id: '/api/auth/sign-in/social'
      path: '/api/auth/sign-in/social'
      fullPath: '/api/auth/sign-in/social'
      preLoaderRoute: typeof ApiAuthSignInSocialRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ComoFuncionaRoute: ComoFuncionaRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  GuardadosRoute: GuardadosRoute,
  LoginRoute: LoginRoute,
  PedirRoute: PedirRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  AuthConfirmRoute: AuthConfirmRoute,
  OficiosSlugRoute: OficiosSlugRoute,
  PedidosIdRoute: PedidosIdRoute,
  ProfissionaisIdRoute: ProfissionaisIdRoute,
  ProfissionalCadastrarRoute: ProfissionalCadastrarRoute,
  ProfissionalPedidosRoute: ProfissionalPedidosRoute,
  OficiosIndexRoute: OficiosIndexRoute,
  PedidosIndexRoute: PedidosIndexRoute,
  ApiAuthRestRoute: ApiAuthRestRoute,
  ApiAuthRest_newRoute: ApiAuthRest_newRoute,
  ApiAuthGetSessionRoute: ApiAuthGetSessionRoute,
  ApiAuthProvidersRoute: ApiAuthProvidersRoute,
  ApiAuthSignOutRoute: ApiAuthSignOutRoute,
  ApiDebugAuthRoute: ApiDebugAuthRoute,
  ApiDebugEnvRoute: ApiDebugEnvRoute,
  ApiPushSubscribeRoute: ApiPushSubscribeRoute,
  ApiPushUnsubscribeRoute: ApiPushUnsubscribeRoute,
  ApiPushVapidStatusRoute: ApiPushVapidStatusRoute,
  ApiUploadAvatarRoute: ApiUploadAvatarRoute,
  ApiUploadDeleteRoute: ApiUploadDeleteRoute,
  ApiUploadPortfolioRoute: ApiUploadPortfolioRoute,
  ApiAuthCallbackGithubRoute: ApiAuthCallbackGithubRoute,
  ApiAuthCallbackGoogleRoute: ApiAuthCallbackGoogleRoute,
  ApiAuthSignInOauth2Route: ApiAuthSignInOauth2Route,
  ApiAuthSignInSocialRoute: ApiAuthSignInSocialRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
