/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ComoFuncionaRouteImport } from './routes/como-funciona'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as GuardadosRouteImport } from './routes/guardados'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PedirRouteImport } from './routes/pedir'
import { Route as OficiosIndexRouteImport } from './routes/oficios.index'
import { Route as OficiosSlugRouteImport } from './routes/oficios.$slug'
import { Route as PedidosIndexRouteImport } from './routes/pedidos.index'
import { Route as PedidosIdRouteImport } from './routes/pedidos.$id'
import { Route as ProfissionaisIdRouteImport } from './routes/profissionais.$id'
import { Route as ProfissionalCadastrarRouteImport } from './routes/profissional.cadastrar'
import { Route as ProfissionalPedidosRouteImport } from './routes/profissional.pedidos'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiPushSubscribeRouteImport } from './routes/api/push/subscribe'
import { Route as ApiPushUnsubscribeRouteImport } from './routes/api/push/unsubscribe'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComoFuncionaRoute = ComoFuncionaRouteImport.update({
  id: '/como-funciona',
  path: '/como-funciona',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const GuardadosRoute = GuardadosRouteImport.update({
  id: '/guardados',
  path: '/guardados',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PedirRoute = PedirRouteImport.update({
  id: '/pedir',
  path: '/pedir',
  getParentRoute: () => rootRouteImport,
} as any)
const OficiosIndexRoute = OficiosIndexRouteImport.update({
  id: '/oficios/',
  path: '/oficios/',
  getParentRoute: () => rootRouteImport,
} as any)
const OficiosSlugRoute = OficiosSlugRouteImport.update({
  id: '/oficios/$slug',
  path: '/oficios/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PedidosIndexRoute = PedidosIndexRouteImport.update({
  id: '/pedidos/',
  path: '/pedidos/',
  getParentRoute: () => rootRouteImport,
} as any)
const PedidosIdRoute = PedidosIdRouteImport.update({
  id: '/pedidos/$id',
  path: '/pedidos/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfissionaisIdRoute = ProfissionaisIdRouteImport.update({
  id: '/profissionais/$id',
  path: '/profissionais/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfissionalCadastrarRoute = ProfissionalCadastrarRouteImport.update({
  id: '/profissional/cadastrar',
  path: '/profissional/cadastrar',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfissionalPedidosRoute = ProfissionalPedidosRouteImport.update({
  id: '/profissional/pedidos',
  path: '/profissional/pedidos',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPushSubscribeRoute = ApiPushSubscribeRouteImport.update({
  id: '/api/push/subscribe',
  path: '/api/push/subscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPushUnsubscribeRoute = ApiPushUnsubscribeRouteImport.update({
  id: '/api/push/unsubscribe',
  path: '/api/push/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/guardados': typeof GuardadosRoute
  '/login': typeof LoginRoute
  '/pedir': typeof PedirRoute
  '/oficios/$slug': typeof OficiosSlugRoute
  '/pedidos/$id': typeof PedidosIdRoute
  '/profissionais/$id': typeof ProfissionaisIdRoute
  '/profissional/cadastrar': typeof ProfissionalCadastrarRoute
  '/profissional/pedidos': typeof ProfissionalPedidosRoute
  '/oficios/': typeof OficiosIndexRoute
  '/pedidos/': typeof PedidosIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/push/subscribe': typeof ApiPushSubscribeRoute
  '/api/push/unsubscribe': typeof ApiPushUnsubscribeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/guardados': typeof GuardadosRoute
  '/login': typeof LoginRoute
  '/pedir': typeof PedirRoute
  '/oficios/$slug': typeof OficiosSlugRoute
  '/pedidos/$id': typeof PedidosIdRoute
  '/profissionais/$id': typeof ProfissionaisIdRoute
  '/profissional/cadastrar': typeof ProfissionalCadastrarRoute
  '/profissional/pedidos': typeof ProfissionalPedidosRoute
  '/oficios': typeof OficiosIndexRoute
  '/pedidos': typeof PedidosIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/push/subscribe': typeof ApiPushSubscribeRoute
  '/api/push/unsubscribe': typeof ApiPushUnsubscribeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/guardados': typeof GuardadosRoute
  '/login': typeof LoginRoute
  '/pedir': typeof PedirRoute
  '/oficios/$slug': typeof OficiosSlugRoute
  '/pedidos/$id': typeof PedidosIdRoute
  '/profissionais/$id': typeof ProfissionaisIdRoute
  '/profissional/cadastrar': typeof ProfissionalCadastrarRoute
  '/profissional/pedidos': typeof ProfissionalPedidosRoute
  '/oficios/': typeof OficiosIndexRoute
  '/pedidos/': typeof PedidosIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/push/subscribe': typeof ApiPushSubscribeRoute
  '/api/push/unsubscribe': typeof ApiPushUnsubscribeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/como-funciona'
    | '/configuracoes'
    | '/guardados'
    | '/login'
    | '/pedir'
    | '/oficios/$slug'
    | '/pedidos/$id'
    | '/profissionais/$id'
    | '/profissional/cadastrar'
    | '/profissional/pedidos'
    | '/oficios/'
    | '/pedidos/'
    | '/api/auth/$'
    | '/api/push/subscribe'
    | '/api/push/unsubscribe'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/como-funciona'
    | '/configuracoes'
    | '/guardados'
    | '/login'
    | '/pedir'
    | '/oficios/$slug'
    | '/pedidos/$id'
    | '/profissionais/$id'
    | '/profissional/cadastrar'
    | '/profissional/pedidos'
    | '/oficios'
    | '/pedidos'
    | '/api/auth/$'
    | '/api/push/subscribe'
    | '/api/push/unsubscribe'
  id:
    | '__root__'
    | '/'
    | '/como-funciona'
    | '/configuracoes'
    | '/guardados'
    | '/login'
    | '/pedir'
    | '/oficios/$slug'
    | '/pedidos/$id'
    | '/profissionais/$id'
    | '/profissional/cadastrar'
    | '/profissional/pedidos'
    | '/oficios/'
    | '/pedidos/'
    | '/api/auth/$'
    | '/api/push/subscribe'
    | '/api/push/unsubscribe'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ComoFuncionaRoute: typeof ComoFuncionaRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  GuardadosRoute: typeof GuardadosRoute
  LoginRoute: typeof LoginRoute
  PedirRoute: typeof PedirRoute
  OficiosSlugRoute: typeof OficiosSlugRoute
  PedidosIdRoute: typeof PedidosIdRoute
  ProfissionaisIdRoute: typeof ProfissionaisIdRoute
  ProfissionalCadastrarRoute: typeof ProfissionalCadastrarRoute
  ProfissionalPedidosRoute: typeof ProfissionalPedidosRoute
  OficiosIndexRoute: typeof OficiosIndexRoute
  PedidosIndexRoute: typeof PedidosIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiPushSubscribeRoute: typeof ApiPushSubscribeRoute
  ApiPushUnsubscribeRoute: typeof ApiPushUnsubscribeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/como-funciona': {
      id: '/como-funciona'
      path: '/como-funciona'
      fullPath: '/como-funciona'
      preLoaderRoute: typeof ComoFuncionaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guardados': {
      id: '/guardados'
      path: '/guardados'
      fullPath: '/guardados'
      preLoaderRoute: typeof GuardadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedir': {
      id: '/pedir'
      path: '/pedir'
      fullPath: '/pedir'
      preLoaderRoute: typeof PedirRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oficios/': {
      id: '/oficios/'
      path: '/oficios'
      fullPath: '/oficios/'
      preLoaderRoute: typeof OficiosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oficios/$slug': {
      id: '/oficios/$slug'
      path: '/oficios/$slug'
      fullPath: '/oficios/$slug'
      preLoaderRoute: typeof OficiosSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedidos/': {
      id: '/pedidos/'
      path: '/pedidos'
      fullPath: '/pedidos/'
      preLoaderRoute: typeof PedidosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedidos/$id': {
      id: '/pedidos/$id'
      path: '/pedidos/$id'
      fullPath: '/pedidos/$id'
      preLoaderRoute: typeof PedidosIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profissionais/$id': {
      id: '/profissionais/$id'
      path: '/profissionais/$id'
      fullPath: '/profissionais/$id'
      preLoaderRoute: typeof ProfissionaisIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profissional/cadastrar': {
      id: '/profissional/cadastrar'
      path: '/profissional/cadastrar'
      fullPath: '/profissional/cadastrar'
      preLoaderRoute: typeof ProfissionalCadastrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profissional/pedidos': {
      id: '/profissional/pedidos'
      path: '/profissional/pedidos'
      fullPath: '/profissional/pedidos'
      preLoaderRoute: typeof ProfissionalPedidosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/push/subscribe': {
      id: '/api/push/subscribe'
      path: '/api/push/subscribe'
      fullPath: '/api/push/subscribe'
      preLoaderRoute: typeof ApiPushSubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/push/unsubscribe': {
      id: '/api/push/unsubscribe'
      path: '/api/push/unsubscribe'
      fullPath: '/api/push/unsubscribe'
      preLoaderRoute: typeof ApiPushUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ComoFuncionaRoute: ComoFuncionaRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  GuardadosRoute: GuardadosRoute,
  LoginRoute: LoginRoute,
  PedirRoute: PedirRoute,
  OficiosSlugRoute: OficiosSlugRoute,
  PedidosIdRoute: PedidosIdRoute,
  ProfissionaisIdRoute: ProfissionaisIdRoute,
  ProfissionalCadastrarRoute: ProfissionalCadastrarRoute,
  ProfissionalPedidosRoute: ProfissionalPedidosRoute,
  OficiosIndexRoute: OficiosIndexRoute,
  PedidosIndexRoute: PedidosIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiPushSubscribeRoute: ApiPushSubscribeRoute,
  ApiPushUnsubscribeRoute: ApiPushUnsubscribeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
